version: '3.1'
services:

  db:
    image: 'postgres:11'
    volumes:
      - ./db-data:/var/lib/postgresql/data
    container_name: "allmonster-db"
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: allmonster-db
volumes:
  db:
  filters:
    driver: local
  proxy-profiles:
    driver: local